### ISSUE TITLE
Base demand with null values

### ISSUE THREAD

**Issue by jmelomunicipia** [KIOS-Research/ImportEpanetInpFiles#36]
I've imported a inp file to shp. In the shp file, the junctions have values in the field demand1. When I export back to inp the field Base Demand only have null values.

**Comment by Mariosmsk** [comment]
Hi @jmelomunicipia, thank you. Sorry for the late answer! 
Fixed in https://github.com/KIOS-Research/ImportEpanetInpFiles/releases/tag/v1.6.6
