### ISSUE TITLE
The repo contains dlls

### ISSUE THREAD

**Issue by pcav** [KIOS-Research/ImportEpanetInpFiles#4]
These are not allowed, as the plugin should only contain free and open source software.

**Comment by Mariosmsk** [comment]
Its ok now!

**Comment by pcav** [comment]
Thanks. Is the plugin functional without the libs?

**Comment by Mariosmsk** [comment]
Yes

**Comment by Mariosmsk** [comment]
Some changes made in github [(ImportEpanetInpFiles),](https://github.com/KIOS-Research/ImportEpanetInpFiles) is it necessary to upload it again in qgis?

**Comment by pcav** [comment]
Please upload a new version, with higher version number.
Thanks.

**Comment by Mariosmsk** [comment]
I have an error now: "There were errors reading plugin package (please check also your plugin's [metadata](https://github.com/KIOS-Research/ImportEpanetInpFiles/blob/master/metadata.txt)). Could not unzip file."  Can you help me? 
Thanks.

**Comment by pcav** [comment]
Probably the name of the file is different from the folder, or from metadata.
Please refer to qgis-dev ML for details. Sorry I can't help more now.

**Comment by Mariosmsk** [comment]
Its ok! Finally, I have uploaded a new version!
